### ISSUE TITLE
Support PCL-XL

### ISSUE THREAD

**Issue by lucianommatos** [michaelknigge/pclbox#1]
Hello. Is there any plan to upgrade this code with support to PCL-XL?
I need to develop a software to extract information like Media Size, Number of Pages, Page Orientation from a raw print file (.PRN) and I'm really lost about how to parse the PCL-XL stream data. Is there any way I can contact you, or something like this, so maybe you can give some ideas, or at least point me to the right direction?
Thanks in advance.

**Comment by AnthonyDParkhurst** [comment]
Hi Luciano,

No, this code is pretty old and PCL-XL is a completely different animal.

I thought about implementing a PCL-XL reader, but time and motivation
interfere.

It is also important to get good documentation on PCL-XL which is a mostly
binary format, but I don't think it was ever publicly released by HP.

I'll see if I can dig up any more info/documentation about it.

Sorry,

Anthony

**Comment by michaelknigge** [comment]
Hi, no... I have no plans for this. PCL-XL is a completely different format so it would not "fit" in this project. You can find some information on PCL-XL on http://www.undocprint.org/formats/page_description_languages/pcl_xl

For an idea "how to parse" you might want to have look on https://github.com/michaelknigge/pclparaphernalia

Since Java and C# are synactically not that different I think you'll have no problems understanding the code...

Sorry.. But this library is more or less "feature complete" so I currently don't plan more features... Sorry...

Hope it helped,
Michael
